### ISSUE TITLE
Repairing at anvil

### ISSUE THREAD

**Issue by FrozenTux** [FrozenTux/CraftGuard2#6]
_Migrated from BukkitDev, ticket #12 by vatrixxx_
http://dev.bukkit.org/server-mods/craftguard/tickets/12-repairing-at-anvil/

Dear FrozenTux,
i have an idea for craftguard. Mojang released minecraft update 1.4.2 and add an anvil.
Could you add an "repairguard"? 
We have jobs on our server for example blacksmith, he can only craft iron items (sword, pickaxe etc.) and sell them. But now is the anvil ingame and the players can repair theirs iron tools for themselves.
And my idea is to give players or jobs the permissions to repair iron items or diamond items.

Greetz VatriXxX

**Comment by FrozenTux** [comment]
Dear VatriXxX,
I'm currently working on Craftguard 2 and more precisely on the addon system.
I think this feature will be very useful since the aim of craftguard is to work as a job system, so i'm accepting this request and will develop it as an addon for CraftGuard2 when it will be out.

Greetings, FrozenTux

**Comment by VatriXxX** [comment]
Okay, thank you.

Greetings, VatriXxX
