### ISSUE TITLE
Metadata not work?

### ISSUE THREAD

**Issue by qqlaiyz** [FrozenTux/CraftGuard2#9]
list.yml Configuration

default:
  permission: woodslab
  ids:
- '126:1'

like this,all wood slab can't craft. ver2.0.3

**Comment by FrozenTux** [comment]
I'll try to reproduce the problem next time I will have my computer (likely tomorrow).
Can you give me more information like the permission plugin you are using and you version of CraftBukkit ?

**Comment by FrozenTux** [comment]
No answer after a looooong time, closing
